# Generated by Gemini, comments added by me and verified from the undertale wiki.
# assets/monsters_data.py

MONSTER_LIST = [
  # =========================================
  #               THE RUINS
  # =========================================
  {
    "id": "dummy", # dummy -- for practice
    "name": "Dummy",
    "hp": 15,
    "atk": 0,
    "def": 0,
    "gold": 0,
    "exp": 0,
    "flavor_text": "A cotton-stuffed doll for combat practice.",
    "random_texts": [
        "Dummy stands around absentmindedly.",
        "Dummy looks like it's going to fall over.",
        "Dummy doesn't have a brain.",
        "Dummy is just kind of there."
    ],
    "acts": {
      "check": "Dummy - ATK 0 DEF 0\nA cotton heart and a button eye.",
      "talk": "You talk to the Dummy... It doesn't seem much for conversation."
    }
  },
  {
    "id": "froggit", # froggit -- a frog
    "name": "Froggit",
    "hp": 30,
    "atk": 4,
    "def": 2,
    "gold": 20,
    "exp": 10,
    "flavor_text": "Life is difficult for this enemy.",
    "random_texts": [
        "Froggit hops to and fro.",
        "The battlefield is filled with the smell of mustard seed.",
        "Froggit croaks callingly.",
        "You are intimidated by Froggit's raw strength. Just kidding.",
        "Froggit doesn't seem to know why it's here."
    ],
    "acts": {
      "check": "Froggit - ATK 4 DEF 2\nLife is difficult for this enemy.",
      "compliment": "Froggit didn't understand what you said, but was flattered anyway.",
      "threaten": "Froggit is shaking...",
      "croak": "Froggit hopped around!"
    }
  },
  {
    "id": "whimsun", #whimsun --  cant fight
    "name": "Whimsun",
    "hp": 10,
    "atk": 3,
    "def": 0,
    "gold": 2,
    "exp": 2,
    "flavor_text": "This monster is too sensitive to fight...",
    "random_texts": [
        "Whimsun is hyperventilating.",
        "Whimsun avoids eye contact.",
        "Whimsun looks like it's about to cry.",
        "Whimsun flutters silently.",
        "You feel a little guilty."
    ],
    "acts": {
      "check": "Whimsun - ATK 3 DEF 0\nToo sensitive to fight...",
      "console": "Whimsun burst into tears and ran away.",
      "terrorize": "Whimsun fainted instantly!"
    }
  },
  {
    "id": "moldsmal", #jelly monster
    "name": "Moldsmal",
    "hp": 50,
    "atk": 6,
    "def": 0,
    "gold": 3,
    "exp": 3,
    "flavor_text": "Stereotypical gelatin.",
    "random_texts": [
        "Moldsmal bubbles quietly.",
        "Moldsmal waits pensively.",
        "The aroma of lime gelatin wafts through.",
        "Moldsmal jiggles slightly."
    ],
    "acts": {
      "check": "Moldsmal - ATK 6 DEF 0\nStereotypical gelatin.",
      "wiggle": "Moldsmal wiggles menacingly.",
      "imitate": "You lie immobile like a slime. Moldsmal respects this."
    }
  },
  {
    "id": "loox", # it "looks"
    "name": "Loox",
    "hp": 50,
    "atk": 6,
    "def": 4,
    "gold": 5,
    "exp": 7,
    "flavor_text": "Don't pick on him.",
    "random_texts": [
        "Loox is looking at you.",
        "Loox gnashes its teeth.",
        "Loox stares into your soul.",
        "Smells like eyedrops."
    ],
    "acts": {
      "check": "Loox - ATK 6 DEF 4\nDon't pick on him. Family name: Eyewalker.",
      "pick_on": "You picked on Loox.",
      "dont_pick_on": "You didn't pick on Loox."
    }
  },
  {
    "id": "vegetoid", # likes veggies
    "name": "Vegetoid",
    "hp": 74,
    "atk": 6,
    "def": 1,
    "gold": 6,
    "exp": 6,
    "flavor_text": "Contains monitor-sized carrots.",
    "random_texts": [
        "Vegetoid gives off a fresh scent.",
        "Vegetoid pulses rhythmically.",
        "Smells like carrots.",
        "Plants can't talk dummy."
    ],
    "acts": {
      "check": "Vegetoid - ATK 6 DEF 1\nServing Size: 1 Monster.",
      "dinner": "You pat your stomach. Vegetoid offers a healthy meal.",
      "devour": "You tried to eat Vegetoid... It wasn't weak enough."
    }
  },
  {
    "id": "migosp", # buggy pookie
    "name": "Migosp",
    "hp": 40,
    "atk": 7,
    "def": 5,
    "gold": 4,
    "exp": 5,
    "flavor_text": "This enemy looks like a bug.",
    "random_texts": [
        "Migosp is knitting its brows.",
        "Migosp tries to look evil.",
        "Migosp is whispering to the others.",
        "Migosp is pretending to be a bad guy."
    ],
    "acts": {
      "check": "Migosp - ATK 7 DEF 5\nIt seems possessed by the urge to dance.",
      "talk": "You talk to Migosp. It ignores you."
    }
  },
  {
    "id": "napstablook", # ghost friend
    "name": "Napstablook",
    "hp": 88,
    "atk": 10,
    "def": 10,
    "gold": 0,
    "exp": -1,
    "flavor_text": "This monster doesn't seem to have a sense of humor...",
    "random_texts": [
        "Napstablook is staring into the distance.",
        "Napstablook pretends to be busy.",
        "The atmosphere is chilly.",
        "Napstablook hums a quiet tune."
    ],
    "acts": {
      "check": "Napstablook - ATK 10 DEF 10\nThis monster doesn't seem to have a sense of humor...",
      "cheer": "You gave Napstablook a patient smile.",
      "flirt": "Napstablook pretends to sleep."
    }
  },

  # =========================================
  #                 SNOWDIN
  # =========================================
  {
    "id": "snowdrake",
    "name": "Snowdrake",
    "hp": 74,
    "atk": 12,
    "def": 2,
    "gold": 18,
    "exp": 22,
    "flavor_text": "This teen comedian fights to keep an audience.",
    "random_texts": [
        "Snowdrake realizes his own name is a pun and freaks out.",
        "Snowdrake is practicing his tight-five.",
        "Snowdrake strikes a pose.",
        "Smells like a snowball."
    ],
    "acts": {
      "check": "Snowdrake - ATK 12 DEF 2\nThis teen comedian fights to keep an audience.",
      "laugh": "You laugh at Snowdrake's bad pun. He beams.",
      "heckle": "You tell Snowdrake he isn't funny."
    }
  },
  {
    "id": "ice_cap",
    "name": "Ice Cap",
    "hp": 48,
    "atk": 11,
    "def": 4,
    "gold": 17,
    "exp": 13,
    "flavor_text": "He wants you to admire his hat.",
    "random_texts": [
        "Ice Cap is thinking about his hat.",
        "Ice Cap touches his hat nervously.",
        "It smells like frozen fabric.",
        "Ice Cap makes sure his hat is still there."
    ],
    "acts": {
      "check": "Ice Cap - ATK 11 DEF 4\nHe wants you to admire his hat.",
      "ignore": "You look away. Ice Cap is desperate for attention.",
      "steal": "You attempt to steal the hat..."
    }
  },
  {
    "id": "lesser_dog",
    "name": "Lesser Dog",
    "hp": 60,
    "atk": 12,
    "def": 2,
    "gold": 25,
    "exp": 18,
    "flavor_text": "Wields a stone dogger.",
    "random_texts": [
        "Lesser Dog is panting.",
        "Lesser Dog barks excitedly.",
        "Lesser Dog is waiting for a command.",
        "Lesser Dog thinks it's going for a walk."
    ],
    "acts": {
      "check": "Lesser Dog - ATK 12 DEF 2\nWields a stone dogger.",
      "pet": "You pet the dog. Its neck extends slightly.",
      "play": "You make a snowball."
    }
  },
  {
    "id": "doggo",
    "name": "Doggo",
    "hp": 70,
    "atk": 13,
    "def": 5,
    "gold": 30,
    "exp": 30,
    "flavor_text": "It moved. It didn't move. It moved.",
    "random_texts": [
        "Doggo is watching the movement of the wind.",
        "Doggo is shaking uncontrollably.",
        "Doggo is checking his periphery.",
        "Doggo smokes a dog treat."
    ],
    "acts": {
      "check": "Doggo - ATK 13 DEF 5\nDon't move an inch!",
      "pet": "Doggo is suspicious of your movement.",
      "ignore": "You stand perfectly still."
    }
  },
  {
    "id": "jerry",
    "name": "Jerry",
    "hp": 80,
    "atk": 0,
    "def": 30,
    "gold": 55,
    "exp": 1,
    "flavor_text": "Everyone knows Jerry.",
    "random_texts": [
        "Jerry eats a powdery donut.",
        "Jerry sneezes without covering his nose.",
        "The wifi here sucks.",
        "Jerry tells everyone he has to go to the bathroom."
    ],
    "acts": {
      "check": "Jerry - ATK 0 DEF 30\nGets a ride from the other monsters.",
      "ditch": "You and the other monsters ditch Jerry."
    }
  },
  {
    "id": "gyftrot",
    "name": "Gyftrot",
    "hp": 118,
    "atk": 14,
    "def": 4,
    "gold": 35,
    "exp": 35,
    "flavor_text": "It's the gift that keeps on giving.",
    "random_texts": [
        "Gyftrot is trembling.",
        "Gyftrot tries to hide.",
        "Gyftrot glares at you.",
        "Smells like pine."
    ],
    "acts": {
      "check": "Gyftrot - ATK 14 DEF 4\nSome teens decorated it as a prank.",
      "undecorate": "You remove a gift from Gyftrot.",
      "gift": "You give Gyftrot a gift."
    }
  },

  # =========================================
  #               WATERFALL
  # =========================================
  {
    "id": "aaron",
    "name": "Aaron",
    "hp": 98,
    "atk": 24,
    "def": 12,
    "gold": 30,
    "exp": 52,
    "flavor_text": "Flexing contest? OK.",
    "random_texts": [
        "Aaron is admiring his own muscles.",
        "Aaron flexes... and a monster flexes back.",
        "Smells like a locker room.",
        "Aaron is sweating."
    ],
    "acts": {
      "check": "Aaron - ATK 24 DEF 12\nThis monster has a lot of horsepower.",
      "flex": "You flex your muscles. Aaron flexes back.",
      "shoo": "You tell Aaron to go away."
    }
  },
  {
    "id": "woshua",
    "name": "Woshua",
    "hp": 70,
    "atk": 25,
    "def": 10,
    "gold": 25,
    "exp": 55,
    "flavor_text": "This monster is very clean.",
    "random_texts": [
        "Woshua is scrubbing the air.",
        "Woshua whistles a clean tune.",
        "Smells like detergent.",
        "Woshua judges your hygiene."
    ],
    "acts": {
      "check": "Woshua - ATK 25 DEF 10\nThis monster is very clean.",
      "clean": "You ask Woshua to clean you.",
      "touch": "You touch Woshua. It is disgusted."
    }
  },
  {
    "id": "moldbygg",
    "name": "Moldbygg",
    "hp": 108,
    "atk": 26,
    "def": 14,
    "gold": 25,
    "exp": 60,
    "flavor_text": "It's a slime mold.",
    "random_texts": [
        "Moldbygg gyrates.",
        "Moldbygg blocks the way.",
        "You hear a squelching sound.",
        "Moldbygg is thinking about slime."
    ],
    "acts": {
      "check": "Moldbygg - ATK 26 DEF 14\nOne size fits all.",
      "unhug": "You tried to unhug the mold...",
      "hug": "You hug the mold."
    }
  },
  {
    "id": "shyren",
    "name": "Shyren",
    "hp": 60,
    "atk": 24,
    "def": 12,
    "gold": 30,
    "exp": 50,
    "flavor_text": "She's hiding in the corner.",
    "random_texts": [
        "Shyren hides in the corner.",
        "Shyren thinks about her future.",
        "Shyren blushes.",
        "Shyren is practicing her singing."
    ],
    "acts": {
      "check": "Shyren - ATK 24 DEF 12\nA talented singer...?",
      "hum": "You hum a melody. Shyren hums along.",
      "smile": "You smile at Shyren."
    }
  },
  {
    "id": "temmie",
    "name": "Temmie",
    "hp": 5,
    "atk": 7,
    "def": -20,
    "gold": 50,
    "exp": 40,
    "flavor_text": "hOI!!!",
    "random_texts": [
        "Temmie vibrates intensely.",
        "Temmie forgot her other attack.",
        "Temmie is petting a hard-boiled egg.",
        "Smells like Temmie Flakes."
    ],
    "acts": {
      "check": "Temmie - ATK 7 DEF -20\nRoves incessantly.",
      "flex": "You flex at Temmie. Temmie is impressed.",
      "talk": "You say hello to Temmie."
    }
  }
]